---
new_page_extension: md
auto_deploy: false
admin_path: ''
webhook_url: 
sections:
- type: heading
  label: My Digital Garden
- type: jekyll-posts
  label: Posts
  create: documents
  templates:
  - titled-post
- type: jekyll-pages
  label: Pages
  create: all
  templates:
  - page
- type: directory
  path: _books
  label: Books
  create: all
  match: "**/*"
  templates:
  - book
- type: document
  path: _data/books.csv
  label: Books Data
  match: "**/*"
upload_dir: ''
public_path: https://digital-garden.s3-us-west-1.amazonaws.com
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_env:
  - JEKYLL_ENV=staging
  preview_output_directory: _site
  install_dependencies_command: bundle install --path vendor/bundle
  preview_docker_image: forestryio/ruby:2.6
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: bundle exec jekyll serve --drafts --unpublished --future
    -d _site
